//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Document_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Upload
    {
        public int UploadId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ResourceUrl { get; set; }
        public string Extension { get; set; }
        public string ResourceName { get; set; }
        public string Tags { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedByDesgination { get; set; }
        public string ApprovedByName { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> LastReviewedDate { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<bool> IsGlobal { get; set; }
        public Nullable<bool> IsPinProtected { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Program Program { get; set; }
        public virtual Project Project { get; set; }
        [NotMapped]
        public string CategoryName { get; set; }
        [NotMapped]
        public string CountryName { get; set; }
        [NotMapped]
        public string EntityName { get; set; }
        [NotMapped]
        public string ProgramName { get; set; }
        [NotMapped]
        public string ProjectName { get; set; }
    }
}
